# New Azure Disk Storage Class (starting from v1.7.2)
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#new-azure-disk-storage-class-starting-from-v172
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: customer-storage
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Shared