kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: customer-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: customerservice
          servicePort: 9000
        path: /customer/*